# Generated by Django 6.0.5 on 2026-05-11 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productorder',
            unique_together={('product', 'order')},
        ),
    ]
