# Generated by Django 6.0.5 on 2026-05-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_dailysummary_order_created_at_order_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysummary',
            name='date',
            field=models.DateField(),
        ),
    ]
