# Generated by Django 6.0.5 on 2026-05-18 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_product_quantity_non_negative'),
        ('store', '0007_alter_dailysummary_date'),
    ]

    operations = [
    ]
